// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoopScoop.Models;

namespace PoopScoop.Solution.Migrations
{
    [DbContext(typeof(PoopScoopContext))]
    partial class PoopScoopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PoopScoop.Models.Poop", b =>
                {
                    b.Property<int>("PoopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Coating")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Color")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Consistency")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Content")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Grade")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Problem")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Solution")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Volume")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PoopId");

                    b.ToTable("Poops");

                    b.HasData(
                        new
                        {
                            PoopId = 1,
                            Coating = "None",
                            Color = "Brown",
                            Consistency = "Soft",
                            Content = "None",
                            Grade = "A",
                            Problem = "No Problems this is a healthy poop.",
                            Solution = "NA",
                            Volume = "Average"
                        },
                        new
                        {
                            PoopId = 2,
                            Coating = "None",
                            Color = "Brown",
                            Consistency = "Liquid",
                            Content = "None",
                            Grade = "B",
                            Problem = "Excessive scratching and inflamed paws sign of grain allergy",
                            Solution = "24 hours fasting, plain food and probiotics",
                            Volume = "Average"
                        },
                        new
                        {
                            PoopId = 3,
                            Coating = "None",
                            Color = "Brown",
                            Consistency = "Soft",
                            Content = "None",
                            Grade = "A-",
                            Problem = "A sudden change may mean your dog is digesting food differently, change in diet, gut inflamation.",
                            Solution = "Monitor for discomfort and speak with your vet if this continues.",
                            Volume = "Above Average"
                        },
                        new
                        {
                            PoopId = 4,
                            Coating = "None",
                            Color = "Brown",
                            Consistency = "Soft",
                            Content = "None",
                            Grade = "A-",
                            Problem = "A sudden change may mean your dog is digesting food differently, change in diet, gut inflamation, or obstruction.",
                            Solution = "Monitor for discomfort and speak with your vet if this continues",
                            Volume = "Below Average"
                        },
                        new
                        {
                            PoopId = 5,
                            Coating = "None",
                            Color = "Brown",
                            Consistency = "Hard",
                            Content = "None",
                            Grade = "B +",
                            Problem = "Dehydration or lack of fibre.",
                            Solution = "Go for a walk with your dog, ensure access to plenty of fresh water",
                            Volume = "Average"
                        },
                        new
                        {
                            PoopId = 6,
                            Coating = "None",
                            Color = "Pink or Purple",
                            Consistency = "Soft",
                            Content = "None",
                            Grade = "F",
                            Problem = "Could indicate HGE or hemorrhagic gastroenteritis.",
                            Solution = "Get an emergency vet appointment",
                            Volume = "Average"
                        },
                        new
                        {
                            PoopId = 7,
                            Coating = "None",
                            Color = "Orange or yellow",
                            Consistency = "Soft",
                            Content = "None",
                            Grade = "D",
                            Problem = "This color can point to an underlying biliary or liver issue",
                            Solution = "Call the vet",
                            Volume = "Average"
                        },
                        new
                        {
                            PoopId = 8,
                            Coating = "None",
                            Color = "Green",
                            Consistency = "Soft",
                            Content = "None",
                            Grade = "C",
                            Problem = "Could be your dog has eaten too much grass, has a gallbladder issue, or has parasites.",
                            Solution = "Monitor for discomfort and speak with a vet if severe or persistent",
                            Volume = "Average"
                        },
                        new
                        {
                            PoopId = 9,
                            Coating = "Greasy",
                            Color = "Grey",
                            Consistency = "Soft",
                            Content = "None",
                            Grade = "B-",
                            Problem = "Could indicate biliary or pancreatic problem.",
                            Solution = "Could be a sign you're feeding too much fat, and may need to switch up their diet",
                            Volume = "Average"
                        },
                        new
                        {
                            PoopId = 10,
                            Coating = "None",
                            Color = "Black",
                            Consistency = "Soft",
                            Content = "None",
                            Grade = "D-",
                            Problem = "Can be a sign of bleeding in the upper GI tract",
                            Solution = "Poop is black because blood has been digested- a sign you should get your dog to a vet.",
                            Volume = "Average"
                        },
                        new
                        {
                            PoopId = 11,
                            Coating = "None",
                            Color = "White",
                            Consistency = "Soft",
                            Content = "None",
                            Grade = "B",
                            Problem = "Maybe a result of diet.",
                            Solution = "Maybe a result of diet, food high in calcium or recent switch to raw food.",
                            Volume = "Average"
                        },
                        new
                        {
                            PoopId = 12,
                            Coating = "None",
                            Color = "Brown",
                            Consistency = "Soft",
                            Content = "Rice-Like Polka-Dots",
                            Grade = "C-",
                            Problem = "Keep an eye out for critters.",
                            Solution = "At the sign of skinny roundworms, or little-rice-shaped tapeworm segments, reach for the dewormer.",
                            Volume = "Average"
                        },
                        new
                        {
                            PoopId = 13,
                            Coating = "None",
                            Color = "Brown",
                            Consistency = "Soft",
                            Content = "Red Streaks",
                            Grade = "D",
                            Problem = "Could indicate presence of blood and needs investigating.",
                            Solution = "If poop is normal in consistency it is likely caused by a tear or trauma in their bottom.",
                            Volume = "Average"
                        },
                        new
                        {
                            PoopId = 14,
                            Coating = "None",
                            Color = "Brown",
                            Consistency = "Soft",
                            Content = "Grass and Random Stuff",
                            Grade = "C",
                            Problem = "Poop including grass or bits of clothing, plastic, and other unusual items.",
                            Solution = "If you items are stuck in their digestive tract get an x-ray pronto",
                            Volume = "Average"
                        },
                        new
                        {
                            PoopId = 15,
                            Coating = "None",
                            Color = "Brown",
                            Consistency = "Soft",
                            Content = "Fur",
                            Grade = "C",
                            Problem = "A sign of over grooming, a dogs way of coping with everything from allergies to stress and anxiety.",
                            Solution = "Reduce stressors and ease them into any changes gradually.",
                            Volume = "Average"
                        },
                        new
                        {
                            PoopId = 16,
                            Coating = "Mucus",
                            Color = "Brown",
                            Consistency = "Soft",
                            Content = "None",
                            Grade = "C-",
                            Problem = "Mucus is a sign of inflamation which can be caused by things such as parasites, food intolerances, and bacterial infections.",
                            Solution = "Food intolerance can require dietary changes and probiotics, in serious cases antibiotics and steroids may be required.",
                            Volume = "Average"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
